### ISSUE TITLE
启用 uBlock Origin 时在 Firefox 上不工作

### ISSUE THREAD

**Issue by linsui** [hewenguang/circle#22]
**遇到的问题**:
启用 uBlock Origin 时在 Firefox 上不工作。这个扩展似乎是注入css，不知为何背景和文字颜色相同。
**问题截图**:
![sshot-008](https://user-images.githubusercontent.com/36977733/111103470-7447ce80-8546-11eb-960d-0ccfa751a28b.png)

**你期望的结果**:

**复现网址**:
我测试的所有网页，包括简书和CSDN,cnblog 都是同样的白屏

**Comment by hewenguang** [comment]
![image](https://user-images.githubusercontent.com/38025280/111629997-d6e1e880-882c-11eb-8726-fa9d41d49676.png)


Circle 使用的类名和他的这个名单中定义的冲突了，太巧了。你可以先禁用这个选项，下一版本把类名修改就好了。点击红色横线右侧的眼睛可以进入代码里看到：

具体的代码是 113459 行的 ##.cc-container

这里的 cc-container 就是 Circle 用来展示数据的容器，被 ublock 隐藏掉了

下一个版本都改成以 Circle 开头的类名就好了

感谢反馈

**Comment by linsui** [comment]
我没有这个列表，不清楚是和其他哪个列表中的定义冲突，所以无法确认，只能等待更新了。非常感谢！

**Comment by hewenguang** [comment]
好的。感谢反馈，这个版本冲冲冲
于2021年3月18日 (周四) 21:16 ***@***.***> 写道:

我没有这个列表，不清楚是和其他哪个列表中的定义冲突，所以无法确认，只能等待更新了。非常感谢！

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/hewenguang/circle/issues/22#issuecomment-801917523>, or
unsubscribe
